### ISSUE TITLE
On php 8.3 list-tests 0.2.4 and php-reporter can't be installed together

### ISSUE THREAD

**Issue by alaczi** [testomatio/php-reporter#5]
With https://github.com/testomatio/php-list-tests/pull/4 list-test was updated to support php8.3

Both packages depends on nategood/httpful:

list-test: "nategood/httpful": "^1.0"
php-reporter: "nategood/httpful": "~0.2"

^1.0 allows versions 1.0.0 and above, but less than 2.0.0.
~0.2 allows versions 0.2.0 and above, but less than 1.0.0.

These do not overlap, hence you can't have both package installed.

**Comment by DavertMik** [comment]
Released 0.4.0

**Comment by TetianaKhomenko** [comment]
@DavertMik @alaczi can this ticket be closed?

**Comment by alaczi** [comment]
> @DavertMik @alaczi can this ticket be closed?

Yes, we can close it, it is possible to install the two packages together now.

Sadly I ran into an erorr with list-tests so I gave up.
